name: QComp - Eld
description: Grupo de Estudos de Computação Quântica
meta_description: "Grupo de Estudos de Computação Quântica"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: "https://qcomp-eld.github.io/"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://qcomp-eld.github.io/"
author: "Your Name"

# Disqus config
disqus-shortname: ""


authors:
  carla_dias:
    name: Carla Dias
    bio: 'Desenvolvedora de Software, gosta de etimologia assim como saber a origem e o por trás de qualquer coisa. Por isso, gosta de Matemática e está se aventurando em Computação Quântica.'
    display_name: Carla Dias
    email: carla.silva@eldorado.org.br
    github: carlamione
    profile_image: '/assets/images/carla_profile.jpg'
  fernando_caletti:
    name: Fernando Caletti
    bio: ''
    display_name: Fernando Caletti
    email: fernando.barros@eldorado.org.br
    github: fecaletti
    profile_image: '/assets/images/profile.png'
  alisson_fumaco:
    name: Alisson Fumaco
    bio: ''
    display_name: Alisson Fumaco
    email: alisson_fumaco@eldorado.org.br
    github: alissonfumaco
    profile_image: '/assets/images/profile.png'